server:
  port: 8079

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: quiz-service
            uri: lb://quiz-service
            predicates:
              - Path=/quiz/*
          - id: question-service
            uri: lb://question-service
            predicates:
              - Path=question/*

          - id: discovery-service
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/web
            filters:
            - SetPath=/
          - id: discovery-service-static
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/**
